// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDza60lb3V0dgGlGM0-xaMx5k8e5aPH9LA',
    appId: '1:448991954233:web:93e6cd8c33c511623094e8',
    messagingSenderId: '448991954233',
    projectId: 'tablein-56028',
    authDomain: 'tablein-56028.firebaseapp.com',
    storageBucket: 'tablein-56028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMvF5SZaCakhRjyBBjfUBzqey5KgU9yc',
    appId: '1:448991954233:android:d36d48469709962e3094e8',
    messagingSenderId: '448991954233',
    projectId: 'tablein-56028',
    storageBucket: 'tablein-56028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7z8jEEuHn8xtjEpiVqJu8aTHOicilKd8',
    appId: '1:448991954233:ios:1038567b1bf76b7c3094e8',
    messagingSenderId: '448991954233',
    projectId: 'tablein-56028',
    storageBucket: 'tablein-56028.appspot.com',
    iosClientId: '448991954233-t6jrp9tg49tslngtuqj2s4206bqpjovd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tablein',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7z8jEEuHn8xtjEpiVqJu8aTHOicilKd8',
    appId: '1:448991954233:ios:25aa8f2e3b7573d23094e8',
    messagingSenderId: '448991954233',
    projectId: 'tablein-56028',
    storageBucket: 'tablein-56028.appspot.com',
    iosClientId: '448991954233-5hhbfl1dnm8hsdsmm45tf20tm96hj3qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tablein.RunnerTests',
  );
}
